In [35]:
%pip install opencv-python
%pip install imageio
%pip install matplotlib


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
  Using cached matplotlib-3.10.7-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
  Using cached contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.61.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (113 kB)
  Using cached kiwisolver-1.4.9-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
  Using cached pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Using cached matplotlib-3.10.7-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_6

In [36]:
import cv2
import numpy as np
import imageio
from matplotlib import pyplot as plt

In [37]:
img = cv2.imread('./data/redPanda.jpg')
img = cv2.cvtColor(img, cv2.COLOR_RGBA2BGR)

In [38]:
img

array([[[ 95, 115,  44],
        [ 98, 119,  50],
        [103, 125,  63],
        ...,
        [164, 167, 182],
        [158, 162, 174],
        [147, 151, 163]],

       [[111, 130,  64],
        [111, 132,  67],
        [112, 133,  74],
        ...,
        [169, 173, 185],
        [167, 171, 183],
        [156, 160, 172]],

       [[128, 146,  86],
        [124, 144,  85],
        [120, 141,  85],
        ...,
        [173, 177, 189],
        [167, 171, 183],
        [155, 159, 170]],

       ...,

       [[  1,   1,   9],
        [  1,   2,   7],
        [  3,   2,   7],
        ...,
        [134, 180, 196],
        [139, 185, 201],
        [137, 183, 199]],

       [[  7,   8,  13],
        [  8,   9,  13],
        [ 11,  11,  13],
        ...,
        [134, 180, 196],
        [132, 178, 194],
        [131, 177, 193]],

       [[ 17,  18,  22],
        [ 17,  18,  20],
        [ 16,  16,  18],
        ...,
        [135, 181, 197],
        [127, 173, 189],
        [125, 171, 187]]

In [39]:
b, g, r = cv2.split(img)
red_channel_img = cv2.merge([np.zeros_like(b), np.zeros_like(g), r])
red_channel_img = cv2.cvtColor(red_channel_img, cv2.COLOR_BGR2RGB)
red_channel_img = cv2.cvtColor(red_channel_img, cv2.COLOR_BGR2GRAY)

blue_channel_img = cv2.merge([b, np.zeros_like(g), np.zeros_like(r)])
blue_channel_img = cv2.cvtColor(blue_channel_img, cv2.COLOR_BGR2RGB)
blue_channel_img = cv2.cvtColor(blue_channel_img, cv2.COLOR_BGR2GRAY)

green_channel_img = cv2.merge([np.zeros_like(b), g, np.zeros_like(r)])
green_channel_img = cv2.cvtColor(green_channel_img, cv2.COLOR_BGR2RGB)
green_channel_img = cv2.cvtColor(green_channel_img, cv2.COLOR_BGR2GRAY)


In [40]:
red_channel_img, green_channel_img, blue_channel_img

(array([[ 5,  6,  7, ..., 21, 20, 19],
        [ 7,  8,  8, ..., 21, 21, 20],
        [10, 10, 10, ..., 22, 21, 19],
        ...,
        [ 1,  1,  1, ..., 22, 23, 23],
        [ 1,  1,  1, ..., 22, 22, 22],
        [ 3,  2,  2, ..., 22, 22, 21]], shape=(166, 250), dtype=uint8),
 array([[ 68,  70,  73, ...,  98,  95,  89],
        [ 76,  77,  78, ..., 102, 100,  94],
        [ 86,  85,  83, ..., 104, 100,  93],
        ...,
        [  1,   1,   1, ..., 106, 109, 107],
        [  5,   5,   6, ..., 106, 104, 104],
        [ 11,  11,   9, ..., 106, 102, 100]], shape=(166, 250), dtype=uint8),
 array([[28, 29, 31, ..., 49, 47, 44],
        [33, 33, 33, ..., 51, 50, 47],
        [38, 37, 36, ..., 52, 50, 46],
        ...,
        [ 0,  0,  1, ..., 40, 42, 41],
        [ 2,  2,  3, ..., 40, 39, 39],
        [ 5,  5,  5, ..., 40, 38, 37]], shape=(166, 250), dtype=uint8))

In [41]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray_img

array([[ 91,  96, 104, ..., 171, 165, 154],
       [108, 110, 113, ..., 176, 174, 163],
       [126, 124, 122, ..., 180, 174, 162],
       ...,
       [  3,   3,   4, ..., 180, 185, 183],
       [  9,  10,  12, ..., 180, 178, 177],
       [ 19,  18,  17, ..., 181, 173, 171]], shape=(166, 250), dtype=uint8)

In [42]:
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(gray_img,kernel,iterations = 1)
dilation = cv2.dilate(gray_img,kernel,iterations = 1)
opening = cv2.morphologyEx(gray_img, cv2.MORPH_OPEN, kernel, iterations=1)

opening


array([[ 91,  96, 104, ..., 171, 165, 154],
       [108, 110, 113, ..., 176, 170, 158],
       [122, 122, 122, ..., 177, 170, 158],
       ...,
       [  3,   3,   4, ..., 178, 173, 171],
       [  3,   3,   4, ..., 178, 173, 171],
       [  3,   3,   4, ..., 178, 173, 171]], shape=(166, 250), dtype=uint8)

In [43]:
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

processed_frames = [
    img_rgb,
    cv2.cvtColor(red_channel_img, cv2.COLOR_GRAY2BGR),
    cv2.cvtColor(green_channel_img, cv2.COLOR_GRAY2BGR),
    cv2.cvtColor(blue_channel_img, cv2.COLOR_GRAY2BGR),
    gray_img, # Already 3-channel, so no further conversion needed
    erosion,  # Already 3-channel, so no further conversion needed
    dilation, # Already 3-channel, so no further conversion needed
    opening   # Already 3-channel, so no further conversion needed
]
print("Image frames prepared successfully.")

Image frames prepared successfully.


In [44]:
import imageio

imageio.mimsave('image_changes.gif', processed_frames, duration=8.5)
print("GIF 'image_changes.gif' created successfully.")

ValueError: all input arrays must have the same shape