In [21]:
import matplotlib.pyplot as plt
import numpy as np
import imageio

In [22]:
shape_vertices = np.array([
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1]
])
display(shape_vertices)

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [0, 1, 1]])

In [23]:
def translate(points, tx, ty):
    translation_matrix = np.array([
        [1, 0, tx],
        [0, 1, ty],
        [0, 0, 1]
    ])
    transformed_points = translation_matrix @ points.T
    return transformed_points.T

def rotate(points, angle_degrees, center=(0, 0)):
    """Applies rotation to a set of points using a transformation matrix."""
    angle_radians = np.radians(angle_degrees)
    cos_angle = np.cos(angle_radians)
    sin_angle = np.sin(angle_radians)

    if center != (0, 0):
        # Translate to origin
        points_translated_to_origin = translate(points, -center[0], -center[1])
    else:
        points_translated_to_origin = points

    rotation_matrix = np.array([
        [cos_angle, -sin_angle, 0],
        [sin_angle, cos_angle, 0],
        [0, 0, 1]
    ])

    rotated_points_translated_to_origin = rotation_matrix @ points_translated_to_origin.T

    if center != (0, 0):
        # Translate back
        rotated_points = translate(rotated_points_translated_to_origin.T, center[0], center[1])
    else:
        rotated_points = rotated_points_translated_to_origin.T

    return rotated_points

def scale(points, sx, sy):
    """Applies scaling to a set of points using a transformation matrix."""
    scaling_matrix = np.array([
        [sx, 0, 0],
        [0, sy, 0],
        [0, 0, 1]
    ])
    scaled_points = scaling_matrix @ points.T
    return scaled_points.T

# Test the functions with the defined square
translated_square = translate(shape_vertices, 2, 3)
rotated_square = rotate(shape_vertices, 45)
scaled_square = scale(shape_vertices, 2, 0.5)

print("Original Square:")
display(shape_vertices)
print("\nTranslated Square:")
display(translated_square)
print("\nRotated Square (45 degrees):")
display(rotated_square)
print("\nScaled Square (sx=2, sy=0.5):")
display(scaled_square)

Original Square:


array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [0, 1, 1]])


Translated Square:


array([[2, 3, 1],
       [3, 3, 1],
       [3, 4, 1],
       [2, 4, 1]])


Rotated Square (45 degrees):


array([[ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 7.07106781e-01,  7.07106781e-01,  1.00000000e+00],
       [ 1.11022302e-16,  1.41421356e+00,  1.00000000e+00],
       [-7.07106781e-01,  7.07106781e-01,  1.00000000e+00]])


Scaled Square (sx=2, sy=0.5):


array([[0. , 0. , 1. ],
       [2. , 0. , 1. ],
       [2. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [24]:
import io
from PIL import Image

frames = []
num_frames = 100
output_filename = "animation.gif"

for i in range(num_frames):
    # Calculate transformation parameters for the current frame
    translation_x = 0.05 * i
    translation_y = 0.03 * i
    rotation_angle = 3.6 * i  # Rotate a full 360 degrees over 100 frames
    scale_x = 1 + 0.01 * i
    scale_y = 1 + 0.005 * i

    # Construct transformation matrices
    translation_matrix = np.array([
        [1, 0, translation_x],
        [0, 1, translation_y],
        [0, 0, 1]
    ])

    angle_radians = np.radians(rotation_angle)
    cos_angle = np.cos(angle_radians)
    sin_angle = np.sin(angle_radians)
    rotation_matrix = np.array([
        [cos_angle, -sin_angle, 0],
        [sin_angle, cos_angle, 0],
        [0, 0, 1]
    ])

    scaling_matrix = np.array([
        [scale_x, 0, 0],
        [0, scale_y, 0],
        [0, 0, 1]
    ])

    # Combine transformation matrices (scale, then rotate, then translate)
    composite_matrix = translation_matrix @ rotation_matrix @ scaling_matrix

    # Apply the composite transformation
    transformed_vertices = (composite_matrix @ shape_vertices.T).T

    # Create and plot the current frame
    fig, ax = plt.subplots(figsize=(6, 6))
    # Plot the original shape for reference (optional)
    # ax.plot(shape_vertices[:, 0], shape_vertices[:, 1], 'k--', alpha=0.5)
    ax.plot(np.append(transformed_vertices[:, 0], transformed_vertices[0, 0]),
            np.append(transformed_vertices[:, 1], transformed_vertices[0, 1]), 'b-')

    # Set axis limits to ensure visibility
    ax.set_xlim(-5, 10)
    ax.set_ylim(-5, 10)
    ax.set_aspect('equal', adjustable='box')
    ax.set_title(f'Frame {i+1}')
    ax.grid(True)

    # Save the figure to a BytesIO buffer
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    img = Image.open(buf)
    frames.append(np.array(img))

    plt.close(fig)

In [25]:
import io
from PIL import Image

frames = []
num_frames = 100
output_filename = "animation.gif"

for i in range(num_frames):
    translation_x = 0.05 * i
    translation_y = 0.03 * i
    rotation_angle = 3.6 * i  # Rotate a full 360 degrees over 100 frames
    scale_x = 1 + 0.01 * i
    scale_y = 1 + 0.005 * i

    translation_matrix = np.array([
        [1, 0, translation_x],
        [0, 1, translation_y],
        [0, 0, 1]
    ])

    angle_radians = np.radians(rotation_angle)
    cos_angle = np.cos(angle_radians)
    sin_angle = np.sin(angle_radians)
    rotation_matrix = np.array([
        [cos_angle, -sin_angle, 0],
        [sin_angle, cos_angle, 0],
        [0, 0, 1]
    ])

    scaling_matrix = np.array([
        [scale_x, 0, 0],
        [0, scale_y, 0],
        [0, 0, 1]
    ])

    composite_matrix = translation_matrix @ rotation_matrix @ scaling_matrix

    transformed_vertices = (composite_matrix @ shape_vertices.T).T

    fig, ax = plt.subplots(figsize=(6, 6))

    ax.plot(np.append(transformed_vertices[:, 0], transformed_vertices[0, 0]),
            np.append(transformed_vertices[:, 1], transformed_vertices[0, 1]), 'b-')

    # Set axis limits to ensure visibility
    ax.set_xlim(-5, 10)
    ax.set_ylim(-5, 10)
    ax.set_aspect('equal', adjustable='box')
    ax.set_title(f'Frame {i+1}')
    ax.grid(True)

    # Save the figure to a BytesIO buffer
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    img = Image.open(buf)
    frames.append(np.array(img))

    plt.close(fig)

In [26]:
imageio.mimsave(output_filename, frames, duration=0.1)
print(f"Animation saved as {output_filename}")

Animation saved as animation.gif
